USE [master]
GO

/****** Object:  Database [ScheDulJ2]    Script Date: 10/17/2018 10:09:47 AM ******/
CREATE DATABASE [ScheDulJ2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ScheDulJ2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.TESTSERVER\MSSQL\DATA\ScheDulJ2.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ScheDulJ2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.TESTSERVER\MSSQL\DATA\ScheDulJ2_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ScheDulJ2] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ScheDulJ2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ScheDulJ2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ScheDulJ2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ScheDulJ2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ScheDulJ2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ScheDulJ2] SET ARITHABORT OFF 
GO

ALTER DATABASE [ScheDulJ2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ScheDulJ2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ScheDulJ2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ScheDulJ2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ScheDulJ2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ScheDulJ2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ScheDulJ2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ScheDulJ2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ScheDulJ2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ScheDulJ2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ScheDulJ2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ScheDulJ2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ScheDulJ2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ScheDulJ2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ScheDulJ2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ScheDulJ2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ScheDulJ2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ScheDulJ2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ScheDulJ2] SET  MULTI_USER 
GO

ALTER DATABASE [ScheDulJ2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ScheDulJ2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ScheDulJ2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ScheDulJ2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ScheDulJ2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ScheDulJ2] SET  READ_WRITE 
GO

